# baseURL = 'https://docs.storj.io/dcs'
baseURL = 'https://storj.github.io/docs/dcs'
title = 'Storj DCS'
contentDir = 'content/dcs'
publishDir = 'public/dcs'

[menu]
  [[menu.before]]
    name = "Node Docs"
    # url = "https://docs.storj.io/node"
    url = 'https://storj.github.io/docs/node'
    weight = -980

[params]
  BookRepo = 'https://github.com/storj/docs'
  BookEditPath = 'edit/main/content/dcs'